[tool.black]
line-length = 99
target-version = ['py310']

[tool.ruff]
exclude = [
    '.git',
    '__pycache__',
    '.vscode',
]
ignore = []
line-length = 99
select = [
    'B',
    'E',
    'F',
    'I',
    'Q',
    'UP',
    'W',
]

[tool.ruff.isort]
force-single-line = true
